# Generated by Django 5.0.2 on 2024-02-15 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_question_user_topic_user_word_user_alter_answer_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='topic',
            name='added_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
