# Generated by Django 5.0.2 on 2024-02-18 16:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_topic_subscribers'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='answer',
            name='public',
        ),
    ]
