# Generated by Django 5.0.2 on 2024-02-28 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_remove_answer_public'),
    ]

    operations = [
        migrations.AddField(
            model_name='word',
            name='word_translate',
            field=models.TextField(default=0),
            preserve_default=False,
        ),
    ]
